# Generated by Django 4.1.5 on 2023-01-23 02:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="mood",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="moodcapture",
            options={"ordering": ("captured_at",)},
        ),
        migrations.RemoveField(
            model_name="location",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="location",
            name="longitude",
        ),
        migrations.AddField(
            model_name="location",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                default="POINT(0.0 0.0)", srid=4326
            ),
        ),
    ]
