# Generated by Django 4.1.5 on 2023-01-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0002_alter_location_options_alter_mood_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
