# Generated by Django 4.1.5 on 2023-01-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0003_alter_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
