# Generated by Django 4.1.5 on 2023-01-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0004_alter_mood_description"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mood",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_mood_name"
            ),
        ),
    ]
