# Generated by Django 4.1.5 on 2023-01-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0005_mood_unique_mood_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("address", "name", "coordinates"),
                name="unique_location_address_name_coordinates",
            ),
        ),
        migrations.AddConstraint(
            model_name="moodcapture",
            constraint=models.UniqueConstraint(
                fields=("location", "mood", "captured_at"),
                name="unique_mood_capture_location_mood_captured_at",
            ),
        ),
    ]
